### ISSUE TITLE
Update wording

### ISSUE THREAD

**Issue by alshyra** [Younup/card#1]
# Update wording

ESN Nantaise ? Je me sens un peu exclu du coup 😅 

https://github.com/Younup/card/blob/c7b7c523d24e5dca412c789b43fb26173eb0bebc/bin/card.js#L22

## Proposal:

Enlever le "Nantaise" ou parler des autres agences

**Comment by necraidan** [comment]
Hello @alshyra, désolé, je viens de voir tout juste ton message.
Bonne idée, je vais mettre à jour avec la nouvelle catch phrase "La néo-ESN agile et humaine au service d’une expertise IT de pointe"
